let data = [
  {
    id: 0,
    gender: "female",
    name: "Olga Sparks",
    email: "olgasparks@aquacine.com",
    balance: "$1,208.66",
    eyeColor: "brown",
    phone: "+1 (995) 512-3472",
    address: "665 Woodbine Street, Thomasville, Maine, 9049",
    marital_status: false
  },
  {
    id: 1,
    gender: "female",
    name: "Hunter Huber",
    email: "hunterhuber@aquacine.com",
    balance: "$2,082.87",
    eyeColor: "brown",
    phone: "+1 (808) 407-3296",
    address: "240 Atlantic Avenue, Neibert, Missouri, 6395",
    marital_status: false
  },
  {
    id: 2,
    gender: "male",
    name: "Hayes Ramirez",
    email: "hayesramirez@aquacine.com",
    balance: "$2,473.38",
    eyeColor: "green",
    phone: "+1 (977) 455-3912",
    address: "361 Aurelia Court, Saddlebrooke, Kentucky, 3811",
    marital_status: false
  },
  {
    id: 3,
    gender: "male",
    name: "Chase Villarreal",
    email: "chasevillarreal@aquacine.com",
    balance: "$1,630.85",
    eyeColor: "brown",
    phone: "+1 (800) 552-3502",
    address: "616 Carlton Avenue, Carlton, Virginia, 7071",
    marital_status: true
  },
  {
    id: 4,
    gender: "male",
    name: "Hollie Reilly",
    email: "holliereilly@aquacine.com",
    balance: "$1,245.20",
    eyeColor: "blue",
    phone: "+1 (902) 599-2031",
    address: "676 Ford Street, Fannett, North Carolina, 1512",
    marital_status: true
  },
  {
    id: 5,
    gender: "female",
    name: "Autumn Owen",
    email: "autumnowen@aquacine.com",
    balance: "$1,097.93",
    eyeColor: "brown",
    phone: "+1 (833) 447-3644",
    address: "995 Holly Street, Witmer, New York, 7849",
    marital_status: false
  },
  {
    id: 6,
    gender: "female",
    name: "Jennings Ratliff",
    email: "jenningsratliff@aquacine.com",
    balance: "$3,781.34",
    eyeColor: "blue",
    phone: "+1 (976) 545-3716",
    address: "799 Jackson Place, Worcester, Michigan, 6306",
    marital_status: true
  },
  {
    id: 7,
    gender: "male",
    name: "Roseann Farmer",
    email: "roseannfarmer@aquacine.com",
    balance: "$2,481.68",
    eyeColor: "green",
    phone: "+1 (965) 446-2046",
    address: "955 Dikeman Street, Sardis, Ohio, 7750",
    marital_status: true
  },
  {
    id: 8,
    gender: "female",
    name: "Tyson Vaughan",
    email: "tysonvaughan@aquacine.com",
    balance: "$2,369.92",
    eyeColor: "blue",
    phone: "+1 (984) 464-2228",
    address: "642 Montauk Court, Indio, Mississippi, 8576",
    marital_status: true
  },
  {
    id: 9,
    gender: "male",
    name: "Higgins Gay",
    email: "higginsgay@aquacine.com",
    balance: "$2,283.55",
    eyeColor: "brown",
    phone: "+1 (932) 584-2588",
    address: "728 Rockaway Avenue, Harold, Arkansas, 4237",
    marital_status: true
  },
  {
    id: 10,
    gender: "male",
    name: "Viola Lyons",
    email: "violalyons@aquacine.com",
    balance: "$1,556.44",
    eyeColor: "brown",
    phone: "+1 (850) 546-3415",
    address: "462 Maple Avenue, Echo, Palau, 4219",
    marital_status: true
  },
  {
    id: 11,
    gender: "female",
    name: "Mercedes Dickson",
    email: "mercedesdickson@aquacine.com",
    balance: "$3,919.76",
    eyeColor: "brown",
    phone: "+1 (916) 444-3584",
    address: "103 Irving Place, Frierson, Idaho, 6211",
    marital_status: false
  },
  {
    id: 12,
    gender: "female",
    name: "Carmela Burch",
    email: "carmelaburch@aquacine.com",
    balance: "$3,030.69",
    eyeColor: "green",
    phone: "+1 (991) 577-3013",
    address: "929 Argyle Road, Seymour, Minnesota, 6407",
    marital_status: true
  },
  {
    id: 13,
    gender: "female",
    name: "Jan Bryan",
    email: "janbryan@aquacine.com",
    balance: "$3,246.40",
    eyeColor: "brown",
    phone: "+1 (917) 528-2227",
    address: "368 Cove Lane, Dixonville, Louisiana, 4455",
    marital_status: false
  },
  {
    id: 14,
    gender: "female",
    name: "Estes Noble",
    email: "estesnoble@aquacine.com",
    balance: "$3,803.22",
    eyeColor: "blue",
    phone: "+1 (911) 430-2863",
    address: "553 Bowery Street, Oberlin, Connecticut, 6489",
    marital_status: false
  },
  {
    id: 15,
    gender: "male",
    name: "Lacy Velazquez",
    email: "lacyvelazquez@aquacine.com",
    balance: "$1,595.40",
    eyeColor: "brown",
    phone: "+1 (903) 468-2451",
    address: "118 Ruby Street, Cleary, Washington, 9283",
    marital_status: true
  },
  {
    id: 16,
    gender: "female",
    name: "Pearlie Branch",
    email: "pearliebranch@aquacine.com",
    balance: "$1,684.96",
    eyeColor: "green",
    phone: "+1 (830) 401-2821",
    address: "460 Newel Street, Adelino, Marshall Islands, 1825",
    marital_status: false
  },
  {
    id: 17,
    gender: "female",
    name: "Olivia Gill",
    email: "oliviagill@aquacine.com",
    balance: "$3,833.51",
    eyeColor: "green",
    phone: "+1 (883) 569-2659",
    address: "242 Stewart Street, Bentonville, Virgin Islands, 498",
    marital_status: true
  },
  {
    id: 18,
    gender: "female",
    name: "Imogene Neal",
    email: "imogeneneal@aquacine.com",
    balance: "$3,680.72",
    eyeColor: "blue",
    phone: "+1 (846) 497-2090",
    address: "405 Mermaid Avenue, Singer, Indiana, 8792",
    marital_status: true
  },
  {
    id: 19,
    gender: "female",
    name: "Brooks Cortez",
    email: "brookscortez@aquacine.com",
    balance: "$1,273.81",
    eyeColor: "green",
    phone: "+1 (941) 511-3141",
    address: "750 Woodside Avenue, Nipinnawasee, California, 7329",
    marital_status: false
  },
  {
    id: 20,
    gender: "male",
    name: "Penny Drake",
    email: "pennydrake@aquacine.com",
    balance: "$3,389.46",
    eyeColor: "brown",
    phone: "+1 (828) 493-2066",
    address: "313 Porter Avenue, Shrewsbury, South Dakota, 1951",
    marital_status: false
  },
  {
    id: 21,
    gender: "female",
    name: "Dixon Bernard",
    email: "dixonbernard@aquacine.com",
    balance: "$3,327.00",
    eyeColor: "brown",
    phone: "+1 (942) 573-3307",
    address:
      "137 Middagh Street, Kanauga, Federated States Of Micronesia, 7443",
    marital_status: false
  },
  {
    id: 22,
    gender: "male",
    name: "Ayala Manning",
    email: "ayalamanning@aquacine.com",
    balance: "$3,813.37",
    eyeColor: "brown",
    phone: "+1 (936) 493-3530",
    address: "510 Baltic Street, Darlington, Nebraska, 5533",
    marital_status: false
  },
  {
    id: 23,
    gender: "male",
    name: "Kirby Mccoy",
    email: "kirbymccoy@aquacine.com",
    balance: "$1,479.75",
    eyeColor: "green",
    phone: "+1 (923) 494-3360",
    address: "685 Dakota Place, Jardine, Oklahoma, 5987",
    marital_status: false
  },
  {
    id: 24,
    gender: "male",
    name: "Minnie Diaz",
    email: "minniediaz@aquacine.com",
    balance: "$1,423.83",
    eyeColor: "brown",
    phone: "+1 (822) 438-3175",
    address: "389 India Street, Ogema, New Jersey, 2473",
    marital_status: true
  },
  {
    id: 25,
    gender: "female",
    name: "Rice Pitts",
    email: "ricepitts@aquacine.com",
    balance: "$3,323.49",
    eyeColor: "green",
    phone: "+1 (900) 482-2448",
    address: "161 Tampa Court, Healy, Arizona, 8197",
    marital_status: false
  },
  {
    id: 26,
    gender: "male",
    name: "Deana Bright",
    email: "deanabright@aquacine.com",
    balance: "$2,424.73",
    eyeColor: "blue",
    phone: "+1 (924) 431-3156",
    address: "107 Huntington Street, Herlong, Utah, 2803",
    marital_status: true
  },
  {
    id: 27,
    gender: "female",
    name: "Mooney Hurst",
    email: "mooneyhurst@aquacine.com",
    balance: "$2,915.45",
    eyeColor: "green",
    phone: "+1 (877) 403-3663",
    address: "438 Vine Street, Lowell, Pennsylvania, 5069",
    marital_status: false
  },
  {
    id: 28,
    gender: "male",
    name: "Bridgette Campbell",
    email: "bridgettecampbell@aquacine.com",
    balance: "$1,505.41",
    eyeColor: "green",
    phone: "+1 (849) 579-3656",
    address: "298 Sullivan Place, Whitmer, Colorado, 1135",
    marital_status: false
  },
  {
    id: 29,
    gender: "female",
    name: "Darlene Dunlap",
    email: "darlenedunlap@aquacine.com",
    balance: "$1,594.91",
    eyeColor: "brown",
    phone: "+1 (880) 551-3714",
    address: "766 Vista Place, Albrightsville, New Hampshire, 4624",
    marital_status: true
  },
  {
    id: 30,
    gender: "female",
    name: "Nikki Aguirre",
    email: "nikkiaguirre@aquacine.com",
    balance: "$2,029.68",
    eyeColor: "green",
    phone: "+1 (832) 426-3218",
    address: "697 Chase Court, Bradenville, Kansas, 7119",
    marital_status: true
  },
  {
    id: 31,
    gender: "female",
    name: "Stevens Ward",
    email: "stevensward@aquacine.com",
    balance: "$3,989.90",
    eyeColor: "brown",
    phone: "+1 (923) 520-2211",
    address: "194 Farragut Place, Homeworth, Wisconsin, 8592",
    marital_status: true
  },
  {
    id: 32,
    gender: "male",
    name: "Strong Cherry",
    email: "strongcherry@aquacine.com",
    balance: "$1,321.37",
    eyeColor: "green",
    phone: "+1 (877) 489-2789",
    address: "346 Hinsdale Street, Ryderwood, Nevada, 6995",
    marital_status: true
  },
  {
    id: 33,
    gender: "male",
    name: "Sheryl Logan",
    email: "sheryllogan@aquacine.com",
    balance: "$1,382.36",
    eyeColor: "green",
    phone: "+1 (979) 412-2164",
    address: "245 Mayfair Drive, Outlook, Wyoming, 4663",
    marital_status: false
  },
  {
    id: 34,
    gender: "female",
    name: "Dianne Hensley",
    email: "diannehensley@aquacine.com",
    balance: "$1,504.42",
    eyeColor: "brown",
    phone: "+1 (878) 425-2993",
    address: "570 Knickerbocker Avenue, Williamson, Guam, 6829",
    marital_status: false
  },
  {
    id: 35,
    gender: "female",
    name: "Cleo Mcconnell",
    email: "cleomcconnell@aquacine.com",
    balance: "$1,734.98",
    eyeColor: "blue",
    phone: "+1 (892) 596-2699",
    address: "682 Laurel Avenue, Kimmell, Georgia, 3210",
    marital_status: false
  },
  {
    id: 36,
    gender: "female",
    name: "Kirsten Holt",
    email: "kirstenholt@aquacine.com",
    balance: "$2,557.73",
    eyeColor: "brown",
    phone: "+1 (861) 442-3290",
    address: "979 Grant Avenue, Muir, Massachusetts, 8484",
    marital_status: true
  },
  {
    id: 37,
    gender: "female",
    name: "Gilliam Wright",
    email: "gilliamwright@aquacine.com",
    balance: "$2,158.70",
    eyeColor: "blue",
    phone: "+1 (968) 475-3006",
    address: "993 Cameron Court, Campo, North Dakota, 1871",
    marital_status: true
  },
  {
    id: 38,
    gender: "male",
    name: "Aimee Baker",
    email: "aimeebaker@aquacine.com",
    balance: "$1,799.96",
    eyeColor: "blue",
    phone: "+1 (995) 572-3344",
    address: "614 Harbor Court, Sattley, New Mexico, 9016",
    marital_status: true
  },
  {
    id: 39,
    gender: "female",
    name: "Nannie Ellison",
    email: "nannieellison@aquacine.com",
    balance: "$3,740.25",
    eyeColor: "brown",
    phone: "+1 (974) 570-2738",
    address: "176 Orient Avenue, Deputy, Northern Mariana Islands, 8008",
    marital_status: false
  },
  {
    id: 40,
    gender: "female",
    name: "Murphy Phelps",
    email: "murphyphelps@aquacine.com",
    balance: "$2,102.59",
    eyeColor: "blue",
    phone: "+1 (957) 589-2958",
    address: "339 Elton Street, Canterwood, Rhode Island, 4507",
    marital_status: true
  },
  {
    id: 41,
    gender: "male",
    name: "Nielsen Giles",
    email: "nielsengiles@aquacine.com",
    balance: "$2,549.80",
    eyeColor: "green",
    phone: "+1 (810) 536-2932",
    address: "944 Herkimer Court, Summertown, Texas, 5595",
    marital_status: true
  },
  {
    id: 42,
    gender: "male",
    name: "Buckner Hardin",
    email: "bucknerhardin@aquacine.com",
    balance: "$2,815.72",
    eyeColor: "green",
    phone: "+1 (812) 551-2009",
    address: "797 Schenck Court, Hayden, West Virginia, 604",
    marital_status: false
  },
  {
    id: 43,
    gender: "male",
    name: "Opal Howe",
    email: "opalhowe@aquacine.com",
    balance: "$3,821.17",
    eyeColor: "green",
    phone: "+1 (944) 560-3207",
    address: "431 Prospect Avenue, Babb, Montana, 4260",
    marital_status: false
  },
  {
    id: 44,
    gender: "female",
    name: "Katie Cole",
    email: "katiecole@aquacine.com",
    balance: "$2,477.24",
    eyeColor: "blue",
    phone: "+1 (940) 424-2383",
    address: "608 Lott Street, Ticonderoga, Iowa, 8238",
    marital_status: false
  },
  {
    id: 45,
    gender: "female",
    name: "Christensen Burgess",
    email: "christensenburgess@aquacine.com",
    balance: "$2,503.82",
    eyeColor: "green",
    phone: "+1 (890) 582-3607",
    address: "340 Moore Street, Macdona, District Of Columbia, 1446",
    marital_status: false
  },
  {
    id: 46,
    gender: "male",
    name: "Wilcox Riley",
    email: "wilcoxriley@aquacine.com",
    balance: "$2,913.37",
    eyeColor: "blue",
    phone: "+1 (867) 453-3520",
    address: "682 Borinquen Pl, Iola, Maryland, 3453",
    marital_status: false
  },
  {
    id: 47,
    gender: "male",
    name: "Christian Hurley",
    email: "christianhurley@aquacine.com",
    balance: "$3,001.70",
    eyeColor: "green",
    phone: "+1 (949) 425-3134",
    address: "191 Reed Street, Cressey, Puerto Rico, 278",
    marital_status: false
  },
  {
    id: 48,
    gender: "female",
    name: "Oneill Donaldson",
    email: "oneilldonaldson@aquacine.com",
    balance: "$1,295.74",
    eyeColor: "green",
    phone: "+1 (878) 600-3960",
    address: "576 Sedgwick Place, Deercroft, Vermont, 212",
    marital_status: true
  },
  {
    id: 49,
    gender: "male",
    name: "Valdez Douglas",
    email: "valdezdouglas@aquacine.com",
    balance: "$1,206.13",
    eyeColor: "blue",
    phone: "+1 (812) 528-2554",
    address: "400 Charles Place, Dunnavant, Alaska, 3074",
    marital_status: true
  },
  {
    id: 50,
    gender: "male",
    name: "Ortiz Mcmahon",
    email: "ortizmcmahon@aquacine.com",
    balance: "$1,286.15",
    eyeColor: "brown",
    phone: "+1 (810) 479-2817",
    address: "961 Bridgewater Street, Rivera, Oregon, 5392",
    marital_status: false
  },
  {
    id: 51,
    gender: "male",
    name: "Flora Fulton",
    email: "florafulton@aquacine.com",
    balance: "$1,381.09",
    eyeColor: "green",
    phone: "+1 (812) 495-3893",
    address: "929 Bay Avenue, Trexlertown, Illinois, 7212",
    marital_status: false
  },
  {
    id: 52,
    gender: "female",
    name: "Carmella Luna",
    email: "carmellaluna@aquacine.com",
    balance: "$1,518.44",
    eyeColor: "green",
    phone: "+1 (867) 534-3014",
    address: "896 Bokee Court, Navarre, Alabama, 5208",
    marital_status: false
  },
  {
    id: 53,
    gender: "female",
    name: "Myra Harrell",
    email: "myraharrell@aquacine.com",
    balance: "$3,392.62",
    eyeColor: "green",
    phone: "+1 (988) 452-3553",
    address: "484 Noel Avenue, Valle, Delaware, 3617",
    marital_status: false
  },
  {
    id: 54,
    gender: "female",
    name: "Verna Berger",
    email: "vernaberger@aquacine.com",
    balance: "$2,145.28",
    eyeColor: "green",
    phone: "+1 (939) 401-2296",
    address: "700 Seacoast Terrace, Lavalette, Hawaii, 2532",
    marital_status: true
  },
  {
    id: 55,
    gender: "female",
    name: "Travis Gilliam",
    email: "travisgilliam@aquacine.com",
    balance: "$2,637.44",
    eyeColor: "green",
    phone: "+1 (838) 444-2421",
    address: "416 Abbey Court, Why, Tennessee, 4456",
    marital_status: false
  },
  {
    id: 56,
    gender: "male",
    name: "Enid Guy",
    email: "enidguy@aquacine.com",
    balance: "$3,869.03",
    eyeColor: "blue",
    phone: "+1 (916) 526-2984",
    address: "500 Gerry Street, Robinson, South Carolina, 523",
    marital_status: false
  },
  {
    id: 57,
    gender: "female",
    name: "Golden Jennings",
    email: "goldenjennings@aquacine.com",
    balance: "$3,847.29",
    eyeColor: "blue",
    phone: "+1 (998) 523-3076",
    address: "288 Eldert Lane, Libertytown, Florida, 3665",
    marital_status: false
  },
  {
    id: 58,
    gender: "male",
    name: "Juanita Porter",
    email: "juanitaporter@aquacine.com",
    balance: "$1,047.58",
    eyeColor: "blue",
    phone: "+1 (843) 407-2478",
    address: "892 Taylor Street, Clinton, Maine, 5026",
    marital_status: true
  },
  {
    id: 59,
    gender: "female",
    name: "Haley Bishop",
    email: "haleybishop@aquacine.com",
    balance: "$2,813.37",
    eyeColor: "green",
    phone: "+1 (851) 503-2592",
    address: "345 Dorset Street, Munjor, Missouri, 3604",
    marital_status: true
  },
  {
    id: 60,
    gender: "female",
    name: "Vang Forbes",
    email: "vangforbes@aquacine.com",
    balance: "$1,795.01",
    eyeColor: "brown",
    phone: "+1 (887) 413-2486",
    address: "679 Stoddard Place, Selma, Kentucky, 9568",
    marital_status: true
  },
  {
    id: 61,
    gender: "male",
    name: "Alexander Buckley",
    email: "alexanderbuckley@aquacine.com",
    balance: "$3,207.26",
    eyeColor: "blue",
    phone: "+1 (836) 454-2508",
    address: "431 Oxford Street, Kennedyville, Virginia, 8360",
    marital_status: false
  },
  {
    id: 62,
    gender: "male",
    name: "Nina Fuentes",
    email: "ninafuentes@aquacine.com",
    balance: "$1,402.93",
    eyeColor: "green",
    phone: "+1 (988) 579-3756",
    address: "938 Clarkson Avenue, Hamilton, North Carolina, 8716",
    marital_status: false
  },
  {
    id: 63,
    gender: "female",
    name: "Cameron Dean",
    email: "camerondean@aquacine.com",
    balance: "$3,525.02",
    eyeColor: "blue",
    phone: "+1 (928) 416-2653",
    address: "556 Chauncey Street, Otranto, New York, 8782",
    marital_status: false
  },
  {
    id: 64,
    gender: "male",
    name: "Abby Lee",
    email: "abbylee@aquacine.com",
    balance: "$3,047.09",
    eyeColor: "green",
    phone: "+1 (990) 552-3984",
    address: "248 Maple Street, Monument, Michigan, 9323",
    marital_status: false
  },
  {
    id: 65,
    gender: "female",
    name: "Howard Carr",
    email: "howardcarr@aquacine.com",
    balance: "$2,925.02",
    eyeColor: "brown",
    phone: "+1 (808) 522-2194",
    address: "573 Navy Street, Advance, Ohio, 5654",
    marital_status: false
  },
  {
    id: 66,
    gender: "male",
    name: "Mcdaniel Rogers",
    email: "mcdanielrogers@aquacine.com",
    balance: "$2,149.75",
    eyeColor: "blue",
    phone: "+1 (825) 505-3369",
    address: "930 Jerome Avenue, Eden, Mississippi, 2307",
    marital_status: false
  },
  {
    id: 67,
    gender: "male",
    name: "Aguilar Frank",
    email: "aguilarfrank@aquacine.com",
    balance: "$3,005.84",
    eyeColor: "brown",
    phone: "+1 (883) 595-3441",
    address: "469 Gerritsen Avenue, Lemoyne, Arkansas, 5729",
    marital_status: false
  },
  {
    id: 68,
    gender: "male",
    name: "Kendra Black",
    email: "kendrablack@aquacine.com",
    balance: "$2,681.71",
    eyeColor: "brown",
    phone: "+1 (980) 500-3806",
    address: "624 Hyman Court, Convent, Palau, 266",
    marital_status: true
  },
  {
    id: 69,
    gender: "female",
    name: "Wilkins Horne",
    email: "wilkinshorne@aquacine.com",
    balance: "$2,800.29",
    eyeColor: "blue",
    phone: "+1 (842) 497-3363",
    address: "561 Forbell Street, Glenbrook, Idaho, 256",
    marital_status: true
  },
  {
    id: 70,
    gender: "male",
    name: "Hahn Snider",
    email: "hahnsnider@aquacine.com",
    balance: "$3,352.28",
    eyeColor: "blue",
    phone: "+1 (900) 467-3709",
    address: "976 Oriental Boulevard, Fairlee, Minnesota, 8700",
    marital_status: true
  },
  {
    id: 71,
    gender: "male",
    name: "Swanson Pratt",
    email: "swansonpratt@aquacine.com",
    balance: "$3,118.33",
    eyeColor: "blue",
    phone: "+1 (963) 487-2321",
    address: "984 Post Court, Orviston, Louisiana, 693",
    marital_status: false
  },
  {
    id: 72,
    gender: "male",
    name: "Villarreal English",
    email: "villarrealenglish@aquacine.com",
    balance: "$2,424.93",
    eyeColor: "brown",
    phone: "+1 (824) 557-3395",
    address: "971 Richardson Street, Gorham, Connecticut, 9632",
    marital_status: true
  },
  {
    id: 73,
    gender: "male",
    name: "Sims Chen",
    email: "simschen@aquacine.com",
    balance: "$2,539.54",
    eyeColor: "green",
    phone: "+1 (837) 585-3389",
    address: "738 Douglass Street, Yonah, Washington, 3861",
    marital_status: true
  },
  {
    id: 74,
    gender: "male",
    name: "Debbie Gamble",
    email: "debbiegamble@aquacine.com",
    balance: "$2,332.53",
    eyeColor: "blue",
    phone: "+1 (817) 554-3098",
    address: "734 Schweikerts Walk, Delshire, Marshall Islands, 2953",
    marital_status: true
  },
  {
    id: 75,
    gender: "female",
    name: "Jennie Dejesus",
    email: "jenniedejesus@aquacine.com",
    balance: "$2,640.02",
    eyeColor: "green",
    phone: "+1 (963) 433-2489",
    address: "144 Brightwater Court, Lisco, Virgin Islands, 4885",
    marital_status: false
  },
  {
    id: 76,
    gender: "female",
    name: "Annette Burt",
    email: "annetteburt@aquacine.com",
    balance: "$1,105.58",
    eyeColor: "green",
    phone: "+1 (964) 470-2935",
    address: "907 Main Street, Hampstead, Indiana, 8240",
    marital_status: false
  },
  {
    id: 77,
    gender: "female",
    name: "Bobbi Harrington",
    email: "bobbiharrington@aquacine.com",
    balance: "$3,184.52",
    eyeColor: "green",
    phone: "+1 (881) 436-3509",
    address: "316 Whitwell Place, Abrams, California, 5471",
    marital_status: false
  },
  {
    id: 78,
    gender: "female",
    name: "Palmer Johnson",
    email: "palmerjohnson@aquacine.com",
    balance: "$1,580.56",
    eyeColor: "brown",
    phone: "+1 (953) 567-3269",
    address: "464 Rochester Avenue, Fingerville, South Dakota, 6705",
    marital_status: true
  },
  {
    id: 79,
    gender: "male",
    name: "Marcie Mayo",
    email: "marciemayo@aquacine.com",
    balance: "$3,645.63",
    eyeColor: "brown",
    phone: "+1 (849) 467-2424",
    address:
      "484 Amherst Street, Carrsville, Federated States Of Micronesia, 7923",
    marital_status: false
  }
];
export default data;
